// <auto-generated />
namespace asp.net_mvc_studentManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddCourses : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCourses));
        
        string IMigrationMetadata.Id
        {
            get { return "201911130336549_AddCourses"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
